# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotbrowser_ui.ui'
#
# Created: Wed Jan 01 16:15:31 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

try:
    from PySide import QtCore, QtGui
except ImportError:
    import sip
    sip.setapi('QString', 2)
    sip.setapi('QVariant', 2)
    from PyQt4 import QtCore, QtGui


class Ui_PlotBrowser(object):
    def setupUi(self, PlotBrowser):
        PlotBrowser.setObjectName("PlotBrowser")
        PlotBrowser.resize(370, 401)
        self.centralwidget = QtGui.QWidget(PlotBrowser)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 371, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.figurestab = QtGui.QWidget()
        self.figurestab.setObjectName("figurestab")
        self.listWidget_figures = QtGui.QListWidget(self.figurestab)
        self.listWidget_figures.setGeometry(QtCore.QRect(10, 10, 261, 111))
        self.listWidget_figures.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listWidget_figures.setObjectName("listWidget_figures")
        self.label_30 = QtGui.QLabel(self.figurestab)
        self.label_30.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.label_30.setObjectName("label_30")
        self.pushButton_makefigure = QtGui.QPushButton(self.figurestab)
        self.pushButton_makefigure.setGeometry(QtCore.QRect(280, 10, 81, 23))
        self.pushButton_makefigure.setObjectName("pushButton_makefigure")
        self.lineEdit_figheight = QtGui.QLineEdit(self.figurestab)
        self.lineEdit_figheight.setGeometry(QtCore.QRect(180, 160, 41, 20))
        self.lineEdit_figheight.setObjectName("lineEdit_figheight")
        self.comboBox_figurefacecolor = QtGui.QComboBox(self.figurestab)
        self.comboBox_figurefacecolor.setGeometry(QtCore.QRect(100, 130, 61, 22))
        self.comboBox_figurefacecolor.setObjectName("comboBox_figurefacecolor")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.comboBox_figurefacecolor.addItem("")
        self.label_38 = QtGui.QLabel(self.figurestab)
        self.label_38.setGeometry(QtCore.QRect(120, 160, 51, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtGui.QLabel(self.figurestab)
        self.label_39.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_39.setObjectName("label_39")
        self.lineEdit_figwidth = QtGui.QLineEdit(self.figurestab)
        self.lineEdit_figwidth.setGeometry(QtCore.QRect(70, 160, 41, 20))
        self.lineEdit_figwidth.setObjectName("lineEdit_figwidth")
        self.pushButton_closefigure = QtGui.QPushButton(self.figurestab)
        self.pushButton_closefigure.setGeometry(QtCore.QRect(280, 100, 81, 23))
        self.pushButton_closefigure.setObjectName("pushButton_closefigure")
        self.pushButton_bringtofront = QtGui.QPushButton(self.figurestab)
        self.pushButton_bringtofront.setGeometry(QtCore.QRect(280, 70, 81, 23))
        self.pushButton_bringtofront.setObjectName("pushButton_bringtofront")
        self.pushButton_refreshlist = QtGui.QPushButton(self.figurestab)
        self.pushButton_refreshlist.setGeometry(QtCore.QRect(280, 40, 81, 23))
        self.pushButton_refreshlist.setObjectName("pushButton_refreshlist")
        self.pushButton_savefigure = QtGui.QPushButton(self.figurestab)
        self.pushButton_savefigure.setGeometry(QtCore.QRect(280, 340, 75, 23))
        self.pushButton_savefigure.setObjectName("pushButton_savefigure")
        self.checkBox_applytorcparams = QtGui.QCheckBox(self.figurestab)
        self.checkBox_applytorcparams.setGeometry(QtCore.QRect(10, 340, 111, 17))
        self.checkBox_applytorcparams.setObjectName("checkBox_applytorcparams")
        self.pushButton_tightlayout = QtGui.QPushButton(self.figurestab)
        self.pushButton_tightlayout.setGeometry(QtCore.QRect(240, 160, 71, 23))
        self.pushButton_tightlayout.setObjectName("pushButton_tightlayout")
        self.label_49 = QtGui.QLabel(self.figurestab)
        self.label_49.setGeometry(QtCore.QRect(170, 130, 41, 16))
        self.label_49.setObjectName("label_49")
        self.doubleSpinBox_figurefacealpha = QtGui.QDoubleSpinBox(self.figurestab)
        self.doubleSpinBox_figurefacealpha.setGeometry(QtCore.QRect(210, 130, 41, 22))
        self.doubleSpinBox_figurefacealpha.setDecimals(1)
        self.doubleSpinBox_figurefacealpha.setMaximum(1.0)
        self.doubleSpinBox_figurefacealpha.setSingleStep(0.1)
        self.doubleSpinBox_figurefacealpha.setProperty("value", 1.0)
        self.doubleSpinBox_figurefacealpha.setObjectName("doubleSpinBox_figurefacealpha")
        self.label_60 = QtGui.QLabel(self.figurestab)
        self.label_60.setGeometry(QtCore.QRect(200, 340, 21, 16))
        self.label_60.setObjectName("label_60")
        self.spinBox_dpi = QtGui.QSpinBox(self.figurestab)
        self.spinBox_dpi.setGeometry(QtCore.QRect(230, 340, 42, 22))
        self.spinBox_dpi.setMinimum(16)
        self.spinBox_dpi.setMaximum(1000)
        self.spinBox_dpi.setSingleStep(16)
        self.spinBox_dpi.setProperty("value", 96)
        self.spinBox_dpi.setObjectName("spinBox_dpi")
        self.tabWidget.addTab(self.figurestab, "")
        self.axestab = QtGui.QWidget()
        self.axestab.setObjectName("axestab")
        self.listWidget_axes = QtGui.QListWidget(self.axestab)
        self.listWidget_axes.setGeometry(QtCore.QRect(10, 180, 181, 101))
        self.listWidget_axes.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listWidget_axes.setObjectName("listWidget_axes")
        self.checkBox_labelright = QtGui.QCheckBox(self.axestab)
        self.checkBox_labelright.setGeometry(QtCore.QRect(270, 210, 70, 17))
        self.checkBox_labelright.setObjectName("checkBox_labelright")
        self.lineEdit_ylabel = QtGui.QLineEdit(self.axestab)
        self.lineEdit_ylabel.setGeometry(QtCore.QRect(240, 260, 121, 20))
        self.lineEdit_ylabel.setObjectName("lineEdit_ylabel")
        self.label_14 = QtGui.QLabel(self.axestab)
        self.label_14.setGeometry(QtCore.QRect(120, 320, 41, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_xlabel = QtGui.QLineEdit(self.axestab)
        self.lineEdit_xlabel.setGeometry(QtCore.QRect(240, 230, 121, 20))
        self.lineEdit_xlabel.setObjectName("lineEdit_xlabel")
        self.comboBox_axisfacecolor = QtGui.QComboBox(self.axestab)
        self.comboBox_axisfacecolor.setGeometry(QtCore.QRect(70, 290, 61, 22))
        self.comboBox_axisfacecolor.setObjectName("comboBox_axisfacecolor")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_axisfacecolor.addItem("")
        self.comboBox_yscale = QtGui.QComboBox(self.axestab)
        self.comboBox_yscale.setGeometry(QtCore.QRect(170, 320, 61, 22))
        self.comboBox_yscale.setObjectName("comboBox_yscale")
        self.comboBox_yscale.addItem("")
        self.comboBox_yscale.addItem("")
        self.comboBox_yscale.addItem("")
        self.label_11 = QtGui.QLabel(self.axestab)
        self.label_11.setGeometry(QtCore.QRect(100, 350, 41, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_xmax = QtGui.QLineEdit(self.axestab)
        self.lineEdit_xmax.setGeometry(QtCore.QRect(140, 350, 41, 20))
        self.lineEdit_xmax.setObjectName("lineEdit_xmax")
        self.label_9 = QtGui.QLabel(self.axestab)
        self.label_9.setGeometry(QtCore.QRect(10, 350, 41, 16))
        self.label_9.setObjectName("label_9")
        self.checkBox_labeltop = QtGui.QCheckBox(self.axestab)
        self.checkBox_labeltop.setGeometry(QtCore.QRect(200, 210, 70, 17))
        self.checkBox_labeltop.setObjectName("checkBox_labeltop")
        self.pushButton_deleteaxes = QtGui.QPushButton(self.axestab)
        self.pushButton_deleteaxes.setGeometry(QtCore.QRect(280, 180, 81, 23))
        self.pushButton_deleteaxes.setObjectName("pushButton_deleteaxes")
        self.label_8 = QtGui.QLabel(self.axestab)
        self.label_8.setGeometry(QtCore.QRect(200, 260, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_13 = QtGui.QLabel(self.axestab)
        self.label_13.setGeometry(QtCore.QRect(10, 320, 41, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_xmin = QtGui.QLineEdit(self.axestab)
        self.lineEdit_xmin.setGeometry(QtCore.QRect(50, 350, 41, 20))
        self.lineEdit_xmin.setObjectName("lineEdit_xmin")
        self.label_33 = QtGui.QLabel(self.axestab)
        self.label_33.setGeometry(QtCore.QRect(10, 290, 51, 16))
        self.label_33.setObjectName("label_33")
        self.label_10 = QtGui.QLabel(self.axestab)
        self.label_10.setGeometry(QtCore.QRect(190, 350, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_7 = QtGui.QLabel(self.axestab)
        self.label_7.setGeometry(QtCore.QRect(200, 230, 41, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_ymax = QtGui.QLineEdit(self.axestab)
        self.lineEdit_ymax.setGeometry(QtCore.QRect(320, 350, 41, 20))
        self.lineEdit_ymax.setObjectName("lineEdit_ymax")
        self.comboBox_xscale = QtGui.QComboBox(self.axestab)
        self.comboBox_xscale.setGeometry(QtCore.QRect(50, 320, 61, 22))
        self.comboBox_xscale.setObjectName("comboBox_xscale")
        self.comboBox_xscale.addItem("")
        self.comboBox_xscale.addItem("")
        self.comboBox_xscale.addItem("")
        self.lineEdit_ymin = QtGui.QLineEdit(self.axestab)
        self.lineEdit_ymin.setGeometry(QtCore.QRect(230, 350, 41, 20))
        self.lineEdit_ymin.setObjectName("lineEdit_ymin")
        self.label_12 = QtGui.QLabel(self.axestab)
        self.label_12.setGeometry(QtCore.QRect(280, 350, 41, 16))
        self.label_12.setObjectName("label_12")
        self.label_40 = QtGui.QLabel(self.axestab)
        self.label_40.setGeometry(QtCore.QRect(240, 320, 51, 16))
        self.label_40.setObjectName("label_40")
        self.comboBox_autoscale = QtGui.QComboBox(self.axestab)
        self.comboBox_autoscale.setGeometry(QtCore.QRect(300, 320, 61, 22))
        self.comboBox_autoscale.setObjectName("comboBox_autoscale")
        self.comboBox_autoscale.addItem("")
        self.comboBox_autoscale.addItem("")
        self.comboBox_autoscale.addItem("")
        self.comboBox_autoscale.addItem("")
        self.comboBox_autoscale.addItem("")
        self.label_50 = QtGui.QLabel(self.axestab)
        self.label_50.setGeometry(QtCore.QRect(140, 290, 41, 16))
        self.label_50.setObjectName("label_50")
        self.doubleSpinBox_axisfacealpha = QtGui.QDoubleSpinBox(self.axestab)
        self.doubleSpinBox_axisfacealpha.setGeometry(QtCore.QRect(180, 290, 41, 22))
        self.doubleSpinBox_axisfacealpha.setDecimals(1)
        self.doubleSpinBox_axisfacealpha.setMaximum(1.0)
        self.doubleSpinBox_axisfacealpha.setSingleStep(0.1)
        self.doubleSpinBox_axisfacealpha.setProperty("value", 1.0)
        self.doubleSpinBox_axisfacealpha.setObjectName("doubleSpinBox_axisfacealpha")
        self.checkBox_sharex = QtGui.QCheckBox(self.axestab)
        self.checkBox_sharex.setGeometry(QtCore.QRect(10, 150, 101, 17))
        self.checkBox_sharex.setObjectName("checkBox_sharex")
        self.pushButton_twinx = QtGui.QPushButton(self.axestab)
        self.pushButton_twinx.setGeometry(QtCore.QRect(230, 150, 61, 23))
        self.pushButton_twinx.setObjectName("pushButton_twinx")
        self.checkBox_sharey = QtGui.QCheckBox(self.axestab)
        self.checkBox_sharey.setGeometry(QtCore.QRect(120, 150, 101, 17))
        self.checkBox_sharey.setObjectName("checkBox_sharey")
        self.pushButton_twiny = QtGui.QPushButton(self.axestab)
        self.pushButton_twiny.setGeometry(QtCore.QRect(300, 150, 61, 23))
        self.pushButton_twiny.setObjectName("pushButton_twiny")
        self.groupBox_3 = QtGui.QGroupBox(self.axestab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 351, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_makesubplot = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_makesubplot.setGeometry(QtCore.QRect(290, 20, 51, 23))
        self.pushButton_makesubplot.setObjectName("pushButton_makesubplot")
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_22.setObjectName("label_22")
        self.spinBox_subplotcolumns = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_subplotcolumns.setGeometry(QtCore.QRect(140, 20, 42, 22))
        self.spinBox_subplotcolumns.setMinimum(1)
        self.spinBox_subplotcolumns.setObjectName("spinBox_subplotcolumns")
        self.spinBox_subplotrows = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_subplotrows.setGeometry(QtCore.QRect(40, 20, 42, 22))
        self.spinBox_subplotrows.setMinimum(1)
        self.spinBox_subplotrows.setObjectName("spinBox_subplotrows")
        self.spinBox_subplotindex = QtGui.QSpinBox(self.groupBox_3)
        self.spinBox_subplotindex.setGeometry(QtCore.QRect(230, 20, 42, 22))
        self.spinBox_subplotindex.setMinimum(1)
        self.spinBox_subplotindex.setObjectName("spinBox_subplotindex")
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(90, 20, 41, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtGui.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(190, 20, 41, 16))
        self.label_32.setObjectName("label_32")
        self.groupBox_4 = QtGui.QGroupBox(self.axestab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 60, 351, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_56 = QtGui.QLabel(self.groupBox_4)
        self.label_56.setGeometry(QtCore.QRect(130, 50, 41, 16))
        self.label_56.setObjectName("label_56")
        self.doubleSpinBox_axesbottom = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_axesbottom.setGeometry(QtCore.QRect(210, 20, 51, 22))
        self.doubleSpinBox_axesbottom.setDecimals(3)
        self.doubleSpinBox_axesbottom.setMaximum(1.0)
        self.doubleSpinBox_axesbottom.setSingleStep(0.1)
        self.doubleSpinBox_axesbottom.setProperty("value", 0.1)
        self.doubleSpinBox_axesbottom.setObjectName("doubleSpinBox_axesbottom")
        self.doubleSpinBox_axeswidth = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_axeswidth.setGeometry(QtCore.QRect(70, 50, 51, 22))
        self.doubleSpinBox_axeswidth.setDecimals(3)
        self.doubleSpinBox_axeswidth.setMaximum(1.0)
        self.doubleSpinBox_axeswidth.setSingleStep(0.1)
        self.doubleSpinBox_axeswidth.setProperty("value", 0.775)
        self.doubleSpinBox_axeswidth.setObjectName("doubleSpinBox_axeswidth")
        self.label_55 = QtGui.QLabel(self.groupBox_4)
        self.label_55.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_55.setObjectName("label_55")
        self.label_52 = QtGui.QLabel(self.groupBox_4)
        self.label_52.setGeometry(QtCore.QRect(130, 20, 71, 16))
        self.label_52.setObjectName("label_52")
        self.label_51 = QtGui.QLabel(self.groupBox_4)
        self.label_51.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_51.setObjectName("label_51")
        self.doubleSpinBox_axesleft = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_axesleft.setGeometry(QtCore.QRect(70, 20, 51, 22))
        self.doubleSpinBox_axesleft.setDecimals(3)
        self.doubleSpinBox_axesleft.setMaximum(1.0)
        self.doubleSpinBox_axesleft.setSingleStep(0.1)
        self.doubleSpinBox_axesleft.setProperty("value", 0.125)
        self.doubleSpinBox_axesleft.setObjectName("doubleSpinBox_axesleft")
        self.doubleSpinBox_axesheight = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_axesheight.setGeometry(QtCore.QRect(210, 50, 51, 22))
        self.doubleSpinBox_axesheight.setDecimals(3)
        self.doubleSpinBox_axesheight.setMaximum(1.0)
        self.doubleSpinBox_axesheight.setSingleStep(0.1)
        self.doubleSpinBox_axesheight.setProperty("value", 0.8)
        self.doubleSpinBox_axesheight.setObjectName("doubleSpinBox_axesheight")
        self.pushButton_makeaxes = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_makeaxes.setGeometry(QtCore.QRect(290, 50, 51, 23))
        self.pushButton_makeaxes.setObjectName("pushButton_makeaxes")
        self.tabWidget.addTab(self.axestab, "")
        self.linestab = QtGui.QWidget()
        self.linestab.setObjectName("linestab")
        self.pushButton_makeline = QtGui.QPushButton(self.linestab)
        self.pushButton_makeline.setGeometry(QtCore.QRect(150, 70, 91, 23))
        self.pushButton_makeline.setObjectName("pushButton_makeline")
        self.label = QtGui.QLabel(self.linestab)
        self.label.setGeometry(QtCore.QRect(10, 10, 16, 16))
        self.label.setObjectName("label")
        self.label_3 = QtGui.QLabel(self.linestab)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 21, 16))
        self.label_3.setObjectName("label_3")
        self.listWidget_lines = QtGui.QListWidget(self.linestab)
        self.listWidget_lines.setGeometry(QtCore.QRect(10, 70, 131, 141))
        self.listWidget_lines.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listWidget_lines.setObjectName("listWidget_lines")
        self.pushButton_deleteline = QtGui.QPushButton(self.linestab)
        self.pushButton_deleteline.setGeometry(QtCore.QRect(260, 70, 101, 23))
        self.pushButton_deleteline.setObjectName("pushButton_deleteline")
        self.lineEdit_x = QtGui.QLineEdit(self.linestab)
        self.lineEdit_x.setGeometry(QtCore.QRect(30, 10, 331, 20))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.lineEdit_y = QtGui.QLineEdit(self.linestab)
        self.lineEdit_y.setGeometry(QtCore.QRect(40, 40, 321, 20))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.pushButton_hline = QtGui.QPushButton(self.linestab)
        self.pushButton_hline.setGeometry(QtCore.QRect(10, 220, 131, 23))
        self.pushButton_hline.setObjectName("pushButton_hline")
        self.pushButton_vline = QtGui.QPushButton(self.linestab)
        self.pushButton_vline.setGeometry(QtCore.QRect(10, 250, 131, 23))
        self.pushButton_vline.setObjectName("pushButton_vline")
        self.groupBox = QtGui.QGroupBox(self.linestab)
        self.groupBox.setGeometry(QtCore.QRect(150, 100, 201, 81))
        self.groupBox.setObjectName("groupBox")
        self.label_23 = QtGui.QLabel(self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_23.setObjectName("label_23")
        self.comboBox_linestyle = QtGui.QComboBox(self.groupBox)
        self.comboBox_linestyle.setGeometry(QtCore.QRect(40, 20, 151, 22))
        self.comboBox_linestyle.setObjectName("comboBox_linestyle")
        self.label_24 = QtGui.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_24.setObjectName("label_24")
        self.doubleSpinBox_linewidth = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_linewidth.setGeometry(QtCore.QRect(50, 50, 42, 22))
        self.doubleSpinBox_linewidth.setDecimals(1)
        self.doubleSpinBox_linewidth.setSingleStep(0.5)
        self.doubleSpinBox_linewidth.setProperty("value", 1.0)
        self.doubleSpinBox_linewidth.setObjectName("doubleSpinBox_linewidth")
        self.label_25 = QtGui.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(100, 50, 41, 16))
        self.label_25.setObjectName("label_25")
        self.comboBox_linecolor = QtGui.QComboBox(self.groupBox)
        self.comboBox_linecolor.setGeometry(QtCore.QRect(130, 50, 61, 22))
        self.comboBox_linecolor.setObjectName("comboBox_linecolor")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.comboBox_linecolor.addItem("")
        self.groupBox_2 = QtGui.QGroupBox(self.linestab)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 190, 201, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_markerstyle = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_markerstyle.setGeometry(QtCore.QRect(40, 20, 151, 22))
        self.comboBox_markerstyle.setObjectName("comboBox_markerstyle")
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.label_27.setObjectName("label_27")
        self.spinBox_markersize = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_markersize.setGeometry(QtCore.QRect(50, 50, 42, 22))
        self.spinBox_markersize.setProperty("value", 6)
        self.spinBox_markersize.setObjectName("spinBox_markersize")
        self.label_28 = QtGui.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(100, 50, 41, 16))
        self.label_28.setObjectName("label_28")
        self.comboBox_markercolor = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_markercolor.setGeometry(QtCore.QRect(130, 50, 61, 22))
        self.comboBox_markercolor.setObjectName("comboBox_markercolor")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.comboBox_markercolor.addItem("")
        self.groupBox_5 = QtGui.QGroupBox(self.linestab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 280, 261, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(70, 20, 41, 16))
        self.label_29.setObjectName("label_29")
        self.comboBox_gridstyle = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_gridstyle.setGeometry(QtCore.QRect(100, 20, 151, 22))
        self.comboBox_gridstyle.setObjectName("comboBox_gridstyle")
        self.label_57 = QtGui.QLabel(self.groupBox_5)
        self.label_57.setGeometry(QtCore.QRect(70, 50, 41, 16))
        self.label_57.setObjectName("label_57")
        self.doubleSpinBox_gridwidth = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.doubleSpinBox_gridwidth.setGeometry(QtCore.QRect(110, 50, 42, 22))
        self.doubleSpinBox_gridwidth.setDecimals(1)
        self.doubleSpinBox_gridwidth.setSingleStep(0.5)
        self.doubleSpinBox_gridwidth.setProperty("value", 0.5)
        self.doubleSpinBox_gridwidth.setObjectName("doubleSpinBox_gridwidth")
        self.label_58 = QtGui.QLabel(self.groupBox_5)
        self.label_58.setGeometry(QtCore.QRect(160, 50, 41, 16))
        self.label_58.setObjectName("label_58")
        self.comboBox_gridcolor = QtGui.QComboBox(self.groupBox_5)
        self.comboBox_gridcolor.setGeometry(QtCore.QRect(190, 50, 61, 22))
        self.comboBox_gridcolor.setObjectName("comboBox_gridcolor")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.comboBox_gridcolor.addItem("")
        self.checkBox_xgrid = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_xgrid.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.checkBox_xgrid.setObjectName("checkBox_xgrid")
        self.checkBox_ygrid = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_ygrid.setGeometry(QtCore.QRect(10, 50, 51, 17))
        self.checkBox_ygrid.setObjectName("checkBox_ygrid")
        self.tabWidget.addTab(self.linestab, "")
        self.spinestickstab = QtGui.QWidget()
        self.spinestickstab.setObjectName("spinestickstab")
        self.label_16 = QtGui.QLabel(self.spinestickstab)
        self.label_16.setGeometry(QtCore.QRect(10, 160, 71, 20))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.spinestickstab)
        self.label_17.setGeometry(QtCore.QRect(10, 130, 71, 16))
        self.label_17.setObjectName("label_17")
        self.doubleSpinBox_ticksmajorlength = QtGui.QDoubleSpinBox(self.spinestickstab)
        self.doubleSpinBox_ticksmajorlength.setGeometry(QtCore.QRect(80, 160, 42, 22))
        self.doubleSpinBox_ticksmajorlength.setDecimals(1)
        self.doubleSpinBox_ticksmajorlength.setSingleStep(0.5)
        self.doubleSpinBox_ticksmajorlength.setProperty("value", 4.0)
        self.doubleSpinBox_ticksmajorlength.setObjectName("doubleSpinBox_ticksmajorlength")
        self.comboBox_ticksdirection = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_ticksdirection.setGeometry(QtCore.QRect(80, 130, 51, 22))
        self.comboBox_ticksdirection.setObjectName("comboBox_ticksdirection")
        self.comboBox_ticksdirection.addItem("")
        self.comboBox_ticksdirection.addItem("")
        self.comboBox_ticksdirection.addItem("")
        self.label_41 = QtGui.QLabel(self.spinestickstab)
        self.label_41.setGeometry(QtCore.QRect(10, 70, 71, 16))
        self.label_41.setObjectName("label_41")
        self.spinBox_numxmajorticks = QtGui.QSpinBox(self.spinestickstab)
        self.spinBox_numxmajorticks.setGeometry(QtCore.QRect(80, 70, 42, 22))
        self.spinBox_numxmajorticks.setProperty("value", 9)
        self.spinBox_numxmajorticks.setObjectName("spinBox_numxmajorticks")
        self.label_42 = QtGui.QLabel(self.spinestickstab)
        self.label_42.setGeometry(QtCore.QRect(190, 70, 71, 16))
        self.label_42.setObjectName("label_42")
        self.spinBox_numymajorticks = QtGui.QSpinBox(self.spinestickstab)
        self.spinBox_numymajorticks.setGeometry(QtCore.QRect(260, 70, 42, 22))
        self.spinBox_numymajorticks.setProperty("value", 9)
        self.spinBox_numymajorticks.setObjectName("spinBox_numymajorticks")
        self.spinBox_numyminorticks = QtGui.QSpinBox(self.spinestickstab)
        self.spinBox_numyminorticks.setGeometry(QtCore.QRect(260, 100, 42, 22))
        self.spinBox_numyminorticks.setObjectName("spinBox_numyminorticks")
        self.label_43 = QtGui.QLabel(self.spinestickstab)
        self.label_43.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_43.setObjectName("label_43")
        self.spinBox_numxminorticks = QtGui.QSpinBox(self.spinestickstab)
        self.spinBox_numxminorticks.setGeometry(QtCore.QRect(80, 100, 42, 22))
        self.spinBox_numxminorticks.setObjectName("spinBox_numxminorticks")
        self.label_44 = QtGui.QLabel(self.spinestickstab)
        self.label_44.setGeometry(QtCore.QRect(190, 100, 71, 16))
        self.label_44.setObjectName("label_44")
        self.doubleSpinBox_ticksmajorwidth = QtGui.QDoubleSpinBox(self.spinestickstab)
        self.doubleSpinBox_ticksmajorwidth.setGeometry(QtCore.QRect(260, 160, 42, 22))
        self.doubleSpinBox_ticksmajorwidth.setDecimals(1)
        self.doubleSpinBox_ticksmajorwidth.setSingleStep(0.1)
        self.doubleSpinBox_ticksmajorwidth.setProperty("value", 0.5)
        self.doubleSpinBox_ticksmajorwidth.setObjectName("doubleSpinBox_ticksmajorwidth")
        self.label_19 = QtGui.QLabel(self.spinestickstab)
        self.label_19.setGeometry(QtCore.QRect(190, 160, 71, 20))
        self.label_19.setObjectName("label_19")
        self.comboBox_ticksdrawbottom = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_ticksdrawbottom.setGeometry(QtCore.QRect(80, 10, 101, 22))
        self.comboBox_ticksdrawbottom.setObjectName("comboBox_ticksdrawbottom")
        self.comboBox_ticksdrawbottom.addItem("")
        self.comboBox_ticksdrawbottom.addItem("")
        self.comboBox_ticksdrawbottom.addItem("")
        self.comboBox_ticksdrawbottom.addItem("")
        self.label_20 = QtGui.QLabel(self.spinestickstab)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_20.setObjectName("label_20")
        self.comboBox_ticksdrawtop = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_ticksdrawtop.setGeometry(QtCore.QRect(80, 40, 101, 22))
        self.comboBox_ticksdrawtop.setObjectName("comboBox_ticksdrawtop")
        self.comboBox_ticksdrawtop.addItem("")
        self.comboBox_ticksdrawtop.addItem("")
        self.comboBox_ticksdrawtop.addItem("")
        self.comboBox_ticksdrawtop.addItem("")
        self.label_45 = QtGui.QLabel(self.spinestickstab)
        self.label_45.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtGui.QLabel(self.spinestickstab)
        self.label_46.setGeometry(QtCore.QRect(190, 10, 71, 16))
        self.label_46.setObjectName("label_46")
        self.comboBox_ticksdrawleft = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_ticksdrawleft.setGeometry(QtCore.QRect(260, 10, 101, 22))
        self.comboBox_ticksdrawleft.setObjectName("comboBox_ticksdrawleft")
        self.comboBox_ticksdrawleft.addItem("")
        self.comboBox_ticksdrawleft.addItem("")
        self.comboBox_ticksdrawleft.addItem("")
        self.comboBox_ticksdrawleft.addItem("")
        self.label_47 = QtGui.QLabel(self.spinestickstab)
        self.label_47.setGeometry(QtCore.QRect(190, 40, 71, 16))
        self.label_47.setObjectName("label_47")
        self.comboBox_ticksdrawright = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_ticksdrawright.setGeometry(QtCore.QRect(260, 40, 101, 22))
        self.comboBox_ticksdrawright.setObjectName("comboBox_ticksdrawright")
        self.comboBox_ticksdrawright.addItem("")
        self.comboBox_ticksdrawright.addItem("")
        self.comboBox_ticksdrawright.addItem("")
        self.comboBox_ticksdrawright.addItem("")
        self.label_15 = QtGui.QLabel(self.spinestickstab)
        self.label_15.setGeometry(QtCore.QRect(10, 250, 51, 16))
        self.label_15.setObjectName("label_15")
        self.doubleSpinBox_spinewidth = QtGui.QDoubleSpinBox(self.spinestickstab)
        self.doubleSpinBox_spinewidth.setGeometry(QtCore.QRect(100, 280, 42, 22))
        self.doubleSpinBox_spinewidth.setDecimals(1)
        self.doubleSpinBox_spinewidth.setSingleStep(0.5)
        self.doubleSpinBox_spinewidth.setProperty("value", 1.0)
        self.doubleSpinBox_spinewidth.setObjectName("doubleSpinBox_spinewidth")
        self.label_59 = QtGui.QLabel(self.spinestickstab)
        self.label_59.setGeometry(QtCore.QRect(10, 220, 71, 16))
        self.label_59.setObjectName("label_59")
        self.comboBox_topspine = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_topspine.setGeometry(QtCore.QRect(100, 250, 71, 22))
        self.comboBox_topspine.setObjectName("comboBox_topspine")
        self.comboBox_topspine.addItem("")
        self.comboBox_topspine.addItem("")
        self.comboBox_topspine.addItem("")
        self.comboBox_topspine.addItem("")
        self.label_37 = QtGui.QLabel(self.spinestickstab)
        self.label_37.setGeometry(QtCore.QRect(10, 280, 81, 20))
        self.label_37.setObjectName("label_37")
        self.comboBox_bottomspine = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_bottomspine.setGeometry(QtCore.QRect(100, 220, 71, 22))
        self.comboBox_bottomspine.setObjectName("comboBox_bottomspine")
        self.comboBox_bottomspine.addItem("")
        self.comboBox_bottomspine.addItem("")
        self.comboBox_bottomspine.addItem("")
        self.comboBox_bottomspine.addItem("")
        self.label_18 = QtGui.QLabel(self.spinestickstab)
        self.label_18.setGeometry(QtCore.QRect(190, 250, 61, 16))
        self.label_18.setObjectName("label_18")
        self.label_61 = QtGui.QLabel(self.spinestickstab)
        self.label_61.setGeometry(QtCore.QRect(190, 220, 71, 16))
        self.label_61.setObjectName("label_61")
        self.comboBox_leftspine = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_leftspine.setGeometry(QtCore.QRect(280, 220, 71, 22))
        self.comboBox_leftspine.setObjectName("comboBox_leftspine")
        self.comboBox_leftspine.addItem("")
        self.comboBox_leftspine.addItem("")
        self.comboBox_leftspine.addItem("")
        self.comboBox_leftspine.addItem("")
        self.comboBox_rightspine = QtGui.QComboBox(self.spinestickstab)
        self.comboBox_rightspine.setGeometry(QtCore.QRect(280, 250, 71, 22))
        self.comboBox_rightspine.setObjectName("comboBox_rightspine")
        self.comboBox_rightspine.addItem("")
        self.comboBox_rightspine.addItem("")
        self.comboBox_rightspine.addItem("")
        self.comboBox_rightspine.addItem("")
        self.checkBox_xminorlabels = QtGui.QCheckBox(self.spinestickstab)
        self.checkBox_xminorlabels.setGeometry(QtCore.QRect(130, 100, 51, 17))
        self.checkBox_xminorlabels.setObjectName("checkBox_xminorlabels")
        self.checkBox_yminorlabels = QtGui.QCheckBox(self.spinestickstab)
        self.checkBox_yminorlabels.setGeometry(QtCore.QRect(310, 100, 51, 17))
        self.checkBox_yminorlabels.setObjectName("checkBox_yminorlabels")
        self.label_34 = QtGui.QLabel(self.spinestickstab)
        self.label_34.setGeometry(QtCore.QRect(10, 190, 71, 20))
        self.label_34.setObjectName("label_34")
        self.doubleSpinBox_ticksminorlength = QtGui.QDoubleSpinBox(self.spinestickstab)
        self.doubleSpinBox_ticksminorlength.setGeometry(QtCore.QRect(80, 190, 42, 22))
        self.doubleSpinBox_ticksminorlength.setDecimals(1)
        self.doubleSpinBox_ticksminorlength.setSingleStep(0.5)
        self.doubleSpinBox_ticksminorlength.setProperty("value", 2.0)
        self.doubleSpinBox_ticksminorlength.setObjectName("doubleSpinBox_ticksminorlength")
        self.doubleSpinBox_ticksminorwidth = QtGui.QDoubleSpinBox(self.spinestickstab)
        self.doubleSpinBox_ticksminorwidth.setGeometry(QtCore.QRect(260, 190, 42, 22))
        self.doubleSpinBox_ticksminorwidth.setDecimals(1)
        self.doubleSpinBox_ticksminorwidth.setSingleStep(0.1)
        self.doubleSpinBox_ticksminorwidth.setProperty("value", 0.5)
        self.doubleSpinBox_ticksminorwidth.setObjectName("doubleSpinBox_ticksminorwidth")
        self.label_48 = QtGui.QLabel(self.spinestickstab)
        self.label_48.setGeometry(QtCore.QRect(190, 190, 71, 20))
        self.label_48.setObjectName("label_48")
        self.tabWidget.addTab(self.spinestickstab, "")
        self.legendtab = QtGui.QWidget()
        self.legendtab.setObjectName("legendtab")
        self.pushButton_legendapply = QtGui.QPushButton(self.legendtab)
        self.pushButton_legendapply.setGeometry(QtCore.QRect(270, 90, 51, 23))
        self.pushButton_legendapply.setObjectName("pushButton_legendapply")
        self.doubleSpinBox_legendalpha = QtGui.QDoubleSpinBox(self.legendtab)
        self.doubleSpinBox_legendalpha.setGeometry(QtCore.QRect(180, 30, 41, 22))
        self.doubleSpinBox_legendalpha.setDecimals(1)
        self.doubleSpinBox_legendalpha.setMaximum(1.0)
        self.doubleSpinBox_legendalpha.setSingleStep(0.1)
        self.doubleSpinBox_legendalpha.setProperty("value", 1.0)
        self.doubleSpinBox_legendalpha.setObjectName("doubleSpinBox_legendalpha")
        self.checkBox_legendshadow = QtGui.QCheckBox(self.legendtab)
        self.checkBox_legendshadow.setGeometry(QtCore.QRect(200, 10, 61, 17))
        self.checkBox_legendshadow.setObjectName("checkBox_legendshadow")
        self.label_53 = QtGui.QLabel(self.legendtab)
        self.label_53.setGeometry(QtCore.QRect(10, 60, 31, 16))
        self.label_53.setObjectName("label_53")
        self.lineEdit_legendtitle = QtGui.QLineEdit(self.legendtab)
        self.lineEdit_legendtitle.setGeometry(QtCore.QRect(40, 60, 281, 20))
        self.lineEdit_legendtitle.setObjectName("lineEdit_legendtitle")
        self.label_35 = QtGui.QLabel(self.legendtab)
        self.label_35.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtGui.QLabel(self.legendtab)
        self.label_36.setGeometry(QtCore.QRect(140, 30, 41, 16))
        self.label_36.setObjectName("label_36")
        self.checkBox_legendframe = QtGui.QCheckBox(self.legendtab)
        self.checkBox_legendframe.setGeometry(QtCore.QRect(60, 10, 51, 17))
        self.checkBox_legendframe.setObjectName("checkBox_legendframe")
        self.comboBox_legendfacecolor = QtGui.QComboBox(self.legendtab)
        self.comboBox_legendfacecolor.setGeometry(QtCore.QRect(70, 30, 61, 22))
        self.comboBox_legendfacecolor.setObjectName("comboBox_legendfacecolor")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.comboBox_legendfacecolor.addItem("")
        self.checkBox_legendfancybox = QtGui.QCheckBox(self.legendtab)
        self.checkBox_legendfancybox.setGeometry(QtCore.QRect(120, 10, 71, 17))
        self.checkBox_legendfancybox.setObjectName("checkBox_legendfancybox")
        self.checkBox_legendon = QtGui.QCheckBox(self.legendtab)
        self.checkBox_legendon.setGeometry(QtCore.QRect(10, 10, 31, 17))
        self.checkBox_legendon.setObjectName("checkBox_legendon")
        self.label_54 = QtGui.QLabel(self.legendtab)
        self.label_54.setGeometry(QtCore.QRect(230, 30, 51, 16))
        self.label_54.setObjectName("label_54")
        self.spinBox_legendcolumns = QtGui.QSpinBox(self.legendtab)
        self.spinBox_legendcolumns.setGeometry(QtCore.QRect(280, 30, 42, 22))
        self.spinBox_legendcolumns.setMinimum(1)
        self.spinBox_legendcolumns.setObjectName("spinBox_legendcolumns")
        self.tabWidget.addTab(self.legendtab, "")
        self.fontstab = QtGui.QWidget()
        self.fontstab.setObjectName("fontstab")
        self.checkBox_fontapplytotitle = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytotitle.setGeometry(QtCore.QRect(60, 40, 41, 17))
        self.checkBox_fontapplytotitle.setObjectName("checkBox_fontapplytotitle")
        self.pushButton_selectfont = QtGui.QPushButton(self.fontstab)
        self.pushButton_selectfont.setGeometry(QtCore.QRect(10, 10, 81, 23))
        self.pushButton_selectfont.setObjectName("pushButton_selectfont")
        self.label_21 = QtGui.QLabel(self.fontstab)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.label_21.setObjectName("label_21")
        self.checkBox_fontapplytolegend = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytolegend.setGeometry(QtCore.QRect(110, 40, 51, 17))
        self.checkBox_fontapplytolegend.setObjectName("checkBox_fontapplytolegend")
        self.checkBox_fontapplytoxlabel = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytoxlabel.setGeometry(QtCore.QRect(170, 40, 51, 17))
        self.checkBox_fontapplytoxlabel.setObjectName("checkBox_fontapplytoxlabel")
        self.checkBox_fontapplytoylabel = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytoylabel.setGeometry(QtCore.QRect(230, 40, 51, 17))
        self.checkBox_fontapplytoylabel.setObjectName("checkBox_fontapplytoylabel")
        self.checkBox_fontapplytoxmajorticklabels = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytoxmajorticklabels.setGeometry(QtCore.QRect(10, 60, 111, 17))
        self.checkBox_fontapplytoxmajorticklabels.setObjectName("checkBox_fontapplytoxmajorticklabels")
        self.checkBox_fontapplytoymajorticklabels = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytoymajorticklabels.setGeometry(QtCore.QRect(120, 60, 111, 17))
        self.checkBox_fontapplytoymajorticklabels.setObjectName("checkBox_fontapplytoymajorticklabels")
        self.pushButton_fontapply = QtGui.QPushButton(self.fontstab)
        self.pushButton_fontapply.setGeometry(QtCore.QRect(230, 100, 51, 23))
        self.pushButton_fontapply.setObjectName("pushButton_fontapply")
        self.comboBox_fontcolor = QtGui.QComboBox(self.fontstab)
        self.comboBox_fontcolor.setGeometry(QtCore.QRect(140, 10, 61, 22))
        self.comboBox_fontcolor.setObjectName("comboBox_fontcolor")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.comboBox_fontcolor.addItem("")
        self.label_114 = QtGui.QLabel(self.fontstab)
        self.label_114.setGeometry(QtCore.QRect(110, 10, 31, 20))
        self.label_114.setObjectName("label_114")
        self.checkBox_fontapplytoyminorticklabels = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytoyminorticklabels.setGeometry(QtCore.QRect(120, 80, 111, 17))
        self.checkBox_fontapplytoyminorticklabels.setObjectName("checkBox_fontapplytoyminorticklabels")
        self.checkBox_fontapplytoxminorticklabels = QtGui.QCheckBox(self.fontstab)
        self.checkBox_fontapplytoxminorticklabels.setGeometry(QtCore.QRect(10, 80, 111, 17))
        self.checkBox_fontapplytoxminorticklabels.setObjectName("checkBox_fontapplytoxminorticklabels")
        self.tabWidget.addTab(self.fontstab, "")
        PlotBrowser.setCentralWidget(self.centralwidget)
        self.actionExit = QtGui.QAction(PlotBrowser)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(PlotBrowser)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_figurefacecolor.setCurrentIndex(0)
        self.comboBox_axisfacecolor.setCurrentIndex(0)
        self.comboBox_autoscale.setCurrentIndex(0)
        self.comboBox_linecolor.setCurrentIndex(13)
        self.comboBox_markercolor.setCurrentIndex(13)
        self.comboBox_gridcolor.setCurrentIndex(3)
        self.comboBox_topspine.setCurrentIndex(0)
        self.comboBox_bottomspine.setCurrentIndex(0)
        self.comboBox_leftspine.setCurrentIndex(0)
        self.comboBox_rightspine.setCurrentIndex(0)
        self.comboBox_legendfacecolor.setCurrentIndex(0)
        self.comboBox_fontcolor.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(PlotBrowser)

    def retranslateUi(self, PlotBrowser):
        PlotBrowser.setWindowTitle(QtGui.QApplication.translate("PlotBrowser", "GraphExplorer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("PlotBrowser", "background color:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_makefigure.setText(QtGui.QApplication.translate("PlotBrowser", "Make figure", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "silver", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(5, QtGui.QApplication.translate("PlotBrowser", "maroon", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(6, QtGui.QApplication.translate("PlotBrowser", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(7, QtGui.QApplication.translate("PlotBrowser", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(8, QtGui.QApplication.translate("PlotBrowser", "olive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(9, QtGui.QApplication.translate("PlotBrowser", "lime", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(10, QtGui.QApplication.translate("PlotBrowser", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(11, QtGui.QApplication.translate("PlotBrowser", "aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(12, QtGui.QApplication.translate("PlotBrowser", "teal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(13, QtGui.QApplication.translate("PlotBrowser", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(14, QtGui.QApplication.translate("PlotBrowser", "navy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(15, QtGui.QApplication.translate("PlotBrowser", "fuchsia", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_figurefacecolor.setItemText(16, QtGui.QApplication.translate("PlotBrowser", "purple", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("PlotBrowser", "height (in):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("PlotBrowser", "width (in):", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_closefigure.setText(QtGui.QApplication.translate("PlotBrowser", "Close figure", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_bringtofront.setText(QtGui.QApplication.translate("PlotBrowser", "Bring to front", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_refreshlist.setText(QtGui.QApplication.translate("PlotBrowser", "Refresh list", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_savefigure.setText(QtGui.QApplication.translate("PlotBrowser", "Save figure", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_applytorcparams.setText(QtGui.QApplication.translate("PlotBrowser", "apply to rcParams", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tightlayout.setText(QtGui.QApplication.translate("PlotBrowser", "Tight layout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("PlotBrowser", "alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("PlotBrowser", "dpi:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.figurestab), QtGui.QApplication.translate("PlotBrowser", "Figures", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_labelright.setText(QtGui.QApplication.translate("PlotBrowser", "label right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("PlotBrowser", "y scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "silver", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(5, QtGui.QApplication.translate("PlotBrowser", "maroon", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(6, QtGui.QApplication.translate("PlotBrowser", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(7, QtGui.QApplication.translate("PlotBrowser", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(8, QtGui.QApplication.translate("PlotBrowser", "olive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(9, QtGui.QApplication.translate("PlotBrowser", "lime", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(10, QtGui.QApplication.translate("PlotBrowser", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(11, QtGui.QApplication.translate("PlotBrowser", "aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(12, QtGui.QApplication.translate("PlotBrowser", "teal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(13, QtGui.QApplication.translate("PlotBrowser", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(14, QtGui.QApplication.translate("PlotBrowser", "navy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(15, QtGui.QApplication.translate("PlotBrowser", "fuchsia", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_axisfacecolor.setItemText(16, QtGui.QApplication.translate("PlotBrowser", "purple", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_yscale.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_yscale.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_yscale.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "symlog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PlotBrowser", "x max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("PlotBrowser", "x min:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_labeltop.setText(QtGui.QApplication.translate("PlotBrowser", "label top", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_deleteaxes.setText(QtGui.QApplication.translate("PlotBrowser", "Delete axes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PlotBrowser", "y label:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("PlotBrowser", "x scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("PlotBrowser", "face color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PlotBrowser", "y min:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PlotBrowser", "x label:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_xscale.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "linear", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_xscale.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_xscale.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "symlog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("PlotBrowser", "y max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("PlotBrowser", "autoscale:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_autoscale.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "auto", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_autoscale.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "equal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_autoscale.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "scaled", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_autoscale.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "tight", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_autoscale.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("PlotBrowser", "alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sharex.setText(QtGui.QApplication.translate("PlotBrowser", "sharex=selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_twinx.setText(QtGui.QApplication.translate("PlotBrowser", "Add twinx", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sharey.setText(QtGui.QApplication.translate("PlotBrowser", "sharey=selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_twiny.setText(QtGui.QApplication.translate("PlotBrowser", "Add twiny", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PlotBrowser", "Add subplot:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_makesubplot.setText(QtGui.QApplication.translate("PlotBrowser", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("PlotBrowser", "rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("PlotBrowser", "columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("PlotBrowser", "index:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PlotBrowser", "Add axes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("PlotBrowser", "height:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("PlotBrowser", "width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("PlotBrowser", "bottom margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("PlotBrowser", "left margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_makeaxes.setText(QtGui.QApplication.translate("PlotBrowser", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.axestab), QtGui.QApplication.translate("PlotBrowser", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_makeline.setText(QtGui.QApplication.translate("PlotBrowser", "Make line", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PlotBrowser", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PlotBrowser", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_deleteline.setText(QtGui.QApplication.translate("PlotBrowser", "Delete line", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_x.setText(QtGui.QApplication.translate("PlotBrowser", "np.linspace(-np.pi,np.pi,100)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_y.setText(QtGui.QApplication.translate("PlotBrowser", "2*np.sin(x)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_hline.setText(QtGui.QApplication.translate("PlotBrowser", "Add horizontal zero line", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_vline.setText(QtGui.QApplication.translate("PlotBrowser", "Add vertical zero line", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PlotBrowser", "Lines:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("PlotBrowser", "style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("PlotBrowser", "width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("PlotBrowser", "color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "silver", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(5, QtGui.QApplication.translate("PlotBrowser", "maroon", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(6, QtGui.QApplication.translate("PlotBrowser", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(7, QtGui.QApplication.translate("PlotBrowser", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(8, QtGui.QApplication.translate("PlotBrowser", "olive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(9, QtGui.QApplication.translate("PlotBrowser", "lime", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(10, QtGui.QApplication.translate("PlotBrowser", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(11, QtGui.QApplication.translate("PlotBrowser", "aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(12, QtGui.QApplication.translate("PlotBrowser", "teal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(13, QtGui.QApplication.translate("PlotBrowser", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(14, QtGui.QApplication.translate("PlotBrowser", "navy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(15, QtGui.QApplication.translate("PlotBrowser", "fuchsia", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_linecolor.setItemText(16, QtGui.QApplication.translate("PlotBrowser", "purple", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PlotBrowser", "Markers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("PlotBrowser", "style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("PlotBrowser", "size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("PlotBrowser", "color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "silver", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(5, QtGui.QApplication.translate("PlotBrowser", "maroon", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(6, QtGui.QApplication.translate("PlotBrowser", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(7, QtGui.QApplication.translate("PlotBrowser", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(8, QtGui.QApplication.translate("PlotBrowser", "olive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(9, QtGui.QApplication.translate("PlotBrowser", "lime", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(10, QtGui.QApplication.translate("PlotBrowser", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(11, QtGui.QApplication.translate("PlotBrowser", "aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(12, QtGui.QApplication.translate("PlotBrowser", "teal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(13, QtGui.QApplication.translate("PlotBrowser", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(14, QtGui.QApplication.translate("PlotBrowser", "navy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(15, QtGui.QApplication.translate("PlotBrowser", "fuchsia", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_markercolor.setItemText(16, QtGui.QApplication.translate("PlotBrowser", "purple", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PlotBrowser", "Grid:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("PlotBrowser", "style:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("PlotBrowser", "width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("PlotBrowser", "color:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "silver", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(5, QtGui.QApplication.translate("PlotBrowser", "maroon", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(6, QtGui.QApplication.translate("PlotBrowser", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(7, QtGui.QApplication.translate("PlotBrowser", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(8, QtGui.QApplication.translate("PlotBrowser", "olive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(9, QtGui.QApplication.translate("PlotBrowser", "lime", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(10, QtGui.QApplication.translate("PlotBrowser", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(11, QtGui.QApplication.translate("PlotBrowser", "aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(12, QtGui.QApplication.translate("PlotBrowser", "teal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(13, QtGui.QApplication.translate("PlotBrowser", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(14, QtGui.QApplication.translate("PlotBrowser", "navy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(15, QtGui.QApplication.translate("PlotBrowser", "fuchsia", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_gridcolor.setItemText(16, QtGui.QApplication.translate("PlotBrowser", "purple", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_xgrid.setText(QtGui.QApplication.translate("PlotBrowser", "x grid", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ygrid.setText(QtGui.QApplication.translate("PlotBrowser", "y grid", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.linestab), QtGui.QApplication.translate("PlotBrowser", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("PlotBrowser", "major length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("PlotBrowser", "tick direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdirection.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "in", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdirection.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "out", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdirection.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "inout", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("PlotBrowser", "x major ticks:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("PlotBrowser", "y major ticks:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("PlotBrowser", "x minor ticks:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("PlotBrowser", "y minor ticks:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("PlotBrowser", "major width:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawbottom.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "ticks only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawbottom.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "tick labels only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawbottom.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "both", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawbottom.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("PlotBrowser", "draw bottom:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawtop.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "ticks only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawtop.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "tick labels only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawtop.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "both", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawtop.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("PlotBrowser", "draw top:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("PlotBrowser", "draw left:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawleft.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "ticks only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawleft.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "tick labels only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawleft.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "both", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawleft.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("PlotBrowser", "draw right:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawright.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "ticks only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawright.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "tick labels only", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawright.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "both", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_ticksdrawright.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("PlotBrowser", "top spine:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("PlotBrowser", "bottom spine:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_topspine.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "outward", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_topspine.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "center", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_topspine.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_topspine.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("PlotBrowser", "spine width:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bottomspine.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "outward", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bottomspine.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "center", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bottomspine.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_bottomspine.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("PlotBrowser", "right spine:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("PlotBrowser", "left spine:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_leftspine.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "outward", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_leftspine.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "center", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_leftspine.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_leftspine.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "off", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rightspine.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "outward", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rightspine.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "center", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rightspine.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "zero", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_rightspine.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "off", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_xminorlabels.setText(QtGui.QApplication.translate("PlotBrowser", "labels", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_yminorlabels.setText(QtGui.QApplication.translate("PlotBrowser", "labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("PlotBrowser", "minor length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("PlotBrowser", "minor width:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spinestickstab), QtGui.QApplication.translate("PlotBrowser", "Spines/Ticks", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_legendapply.setText(QtGui.QApplication.translate("PlotBrowser", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_legendshadow.setText(QtGui.QApplication.translate("PlotBrowser", "shadow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("PlotBrowser", "title:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("PlotBrowser", "face color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("PlotBrowser", "alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_legendframe.setText(QtGui.QApplication.translate("PlotBrowser", "frame", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "silver", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(5, QtGui.QApplication.translate("PlotBrowser", "maroon", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(6, QtGui.QApplication.translate("PlotBrowser", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(7, QtGui.QApplication.translate("PlotBrowser", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(8, QtGui.QApplication.translate("PlotBrowser", "olive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(9, QtGui.QApplication.translate("PlotBrowser", "lime", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(10, QtGui.QApplication.translate("PlotBrowser", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(11, QtGui.QApplication.translate("PlotBrowser", "aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(12, QtGui.QApplication.translate("PlotBrowser", "teal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(13, QtGui.QApplication.translate("PlotBrowser", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(14, QtGui.QApplication.translate("PlotBrowser", "navy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(15, QtGui.QApplication.translate("PlotBrowser", "fuchsia", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_legendfacecolor.setItemText(16, QtGui.QApplication.translate("PlotBrowser", "purple", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_legendfancybox.setText(QtGui.QApplication.translate("PlotBrowser", "fancybox", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_legendon.setText(QtGui.QApplication.translate("PlotBrowser", "on", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("PlotBrowser", "columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.legendtab), QtGui.QApplication.translate("PlotBrowser", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytotitle.setText(QtGui.QApplication.translate("PlotBrowser", "title", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_selectfont.setText(QtGui.QApplication.translate("PlotBrowser", "Select font...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("PlotBrowser", "Apply to:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytolegend.setText(QtGui.QApplication.translate("PlotBrowser", "legend", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytoxlabel.setText(QtGui.QApplication.translate("PlotBrowser", "x label", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytoylabel.setText(QtGui.QApplication.translate("PlotBrowser", "y label", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytoxmajorticklabels.setText(QtGui.QApplication.translate("PlotBrowser", "x major tick labels", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytoymajorticklabels.setText(QtGui.QApplication.translate("PlotBrowser", "y major tick labels", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_fontapply.setText(QtGui.QApplication.translate("PlotBrowser", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(0, QtGui.QApplication.translate("PlotBrowser", "white", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(1, QtGui.QApplication.translate("PlotBrowser", "silver", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(2, QtGui.QApplication.translate("PlotBrowser", "grey", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(3, QtGui.QApplication.translate("PlotBrowser", "black", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(4, QtGui.QApplication.translate("PlotBrowser", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(5, QtGui.QApplication.translate("PlotBrowser", "maroon", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(6, QtGui.QApplication.translate("PlotBrowser", "orange", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(7, QtGui.QApplication.translate("PlotBrowser", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(8, QtGui.QApplication.translate("PlotBrowser", "olive", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(9, QtGui.QApplication.translate("PlotBrowser", "lime", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(10, QtGui.QApplication.translate("PlotBrowser", "green", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(11, QtGui.QApplication.translate("PlotBrowser", "aqua", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(12, QtGui.QApplication.translate("PlotBrowser", "teal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(13, QtGui.QApplication.translate("PlotBrowser", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(14, QtGui.QApplication.translate("PlotBrowser", "navy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(15, QtGui.QApplication.translate("PlotBrowser", "fuchsia", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_fontcolor.setItemText(16, QtGui.QApplication.translate("PlotBrowser", "purple", None, QtGui.QApplication.UnicodeUTF8))
        self.label_114.setText(QtGui.QApplication.translate("PlotBrowser", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytoyminorticklabels.setText(QtGui.QApplication.translate("PlotBrowser", "y minor tick labels", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_fontapplytoxminorticklabels.setText(QtGui.QApplication.translate("PlotBrowser", "x minor tick labels", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fontstab), QtGui.QApplication.translate("PlotBrowser", "Fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("PlotBrowser", "Exit", None, QtGui.QApplication.UnicodeUTF8))

